# Generated by Django 5.2.4 on 2025-07-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ratings', models.IntegerField()),
                ('purchase_date', models.DateField()),
                ('item_variation', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('review_content', models.TextField()),
                ('has_image', models.BooleanField()),
                ('subreview', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
