FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set work directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY backend/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

# Commented for docker-compose
# EXPOSE 8000

# Copy Django project files
# Commented for docker-compose
COPY backend/. /app/

EXPOSE 8000

COPY backend/docker-entry.sh /app/docker-entry.sh
RUN chmod +x /app/docker-entry.sh
ENTRYPOINT ["/app/docker-entry.sh"]



# # Apply migrations
# RUN python manage.py migrate

# # Collect static files (WhiteNoise-compatible)
# RUN python manage.py collectstatic --noinput

# # Init superuser
# RUN python manage.py init_superuser

# # Default command (will be overriden with docker-compose)
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
