version: "3.9"

services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/dev.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}
      interval: 30s
      timeout: 20s
      start_period: 10s
      retries: 5

  web:
    build:
      context: .
      dockerfile: dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      
    env_file:
      - ./backend/dev.env
    environment:
      - POSTGRES_HOST=db
  micro-service:
    build:
      context: .
      dockerfile: dockerfile.microservice
    volumes:
      - ./classification_service:/app
    ports:
      - "5000:5000"
    depends_on:
      - web

volumes:
  postgres_data:
