name: Main Branch CI Pipeline

on: 
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Setup and Test Postgres and Django
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Load environment variables from dev.env
        uses: falti/dotenv-action@v1
        with:
          path: backend/dev.env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  