name: Microservice CI

on:
  push:
    paths:
      - 'classification_service/**'
  pull_request:
    paths:
      - 'classification_service/**'

jobs:
  microservice-ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: classification_service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run tests
        run: |
          python main.py